# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(948, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.mainSongView = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainSongView.sizePolicy().hasHeightForWidth())
        self.mainSongView.setSizePolicy(sizePolicy)
        self.mainSongView.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mainSongView.setObjectName("mainSongView")
        self.horizontalLayout_7.addWidget(self.mainSongView)
        self.songScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.songScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.songScrollBar.setObjectName("songScrollBar")
        self.horizontalLayout_7.addWidget(self.songScrollBar)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_3.setObjectName("formLayout_3")
        self.betaLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.betaLabel_3.setObjectName("betaLabel_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.betaLabel_3)
        self.beatIn_3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.beatIn_3.setObjectName("beatIn_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.beatIn_3)
        self.timeLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.timeLabel_3.setObjectName("timeLabel_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.timeLabel_3)
        self.timeIn_3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.timeIn_3.setObjectName("timeIn_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.timeIn_3)
        self.noteIndexLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.noteIndexLabel_3.setObjectName("noteIndexLabel_3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.noteIndexLabel_3)
        self.indexIn_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.indexIn_3.setObjectName("indexIn_3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.indexIn_3)
        self.noteLayerLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.noteLayerLabel_3.setObjectName("noteLayerLabel_3")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.noteLayerLabel_3)
        self.layerIn_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.layerIn_3.setObjectName("layerIn_3")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.layerIn_3)
        self.noteTypeLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.noteTypeLabel_3.setObjectName("noteTypeLabel_3")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.noteTypeLabel_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.mineBtn_3 = QtWidgets.QToolButton(self.centralwidget)
        self.mineBtn_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../graphics/mine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mineBtn_3.setIcon(icon)
        self.mineBtn_3.setIconSize(QtCore.QSize(32, 32))
        self.mineBtn_3.setCheckable(True)
        self.mineBtn_3.setObjectName("mineBtn_3")
        self.horizontalLayout_6.addWidget(self.mineBtn_3)
        self.redBtn_3 = QtWidgets.QToolButton(self.centralwidget)
        self.redBtn_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../graphics/red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.redBtn_3.setIcon(icon1)
        self.redBtn_3.setIconSize(QtCore.QSize(32, 32))
        self.redBtn_3.setCheckable(True)
        self.redBtn_3.setObjectName("redBtn_3")
        self.horizontalLayout_6.addWidget(self.redBtn_3)
        self.bluBtn_3 = QtWidgets.QToolButton(self.centralwidget)
        self.bluBtn_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../graphics/blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bluBtn_3.setIcon(icon2)
        self.bluBtn_3.setIconSize(QtCore.QSize(32, 32))
        self.bluBtn_3.setCheckable(True)
        self.bluBtn_3.setObjectName("bluBtn_3")
        self.horizontalLayout_6.addWidget(self.bluBtn_3)
        self.formLayout_3.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.cutDirLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.cutDirLabel_3.setObjectName("cutDirLabel_3")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.cutDirLabel_3)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.upLeftBtn_3 = QtWidgets.QToolButton(self.centralwidget)
        self.upLeftBtn_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../graphics/upRight.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upLeftBtn_3.setIcon(icon3)
        self.upLeftBtn_3.setIconSize(QtCore.QSize(32, 32))
        self.upLeftBtn_3.setCheckable(True)
        self.upLeftBtn_3.setObjectName("upLeftBtn_3")
        self.gridLayout_3.addWidget(self.upLeftBtn_3, 2, 2, 1, 1)
        self.downRightBtn_3 = QtWidgets.QToolButton(self.centralwidget)
        self.downRightBtn_3.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../graphics/downRight.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downRightBtn_3.setIcon(icon4)
        self.downRightBtn_3.setIconSize(QtCore.QSize(32, 32))
        self.downRightBtn_3.setCheckable(True)
        self.downRightBtn_3.setObjectName("downRightBtn_3")
        self.gridLayout_3.addWidget(self.downRightBtn_3, 0, 0, 1, 1)
        self.rightBtn_3 = QtWidgets.QToolButton(self.centralwidget)
        self.rightBtn_3.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../graphics/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightBtn_3.setIcon(icon5)
        self.rightBtn_3.setIconSize(QtCore.QSize(32, 32))
        self.rightBtn_3.setCheckable(True)
        self.rightBtn_3.setObjectName("rightBtn_3")
        self.gridLayout_3.addWidget(self.rightBtn_3, 1, 0, 1, 1)
        self.downBtn_3 = QtWidgets.QToolButton(self.centralwidget)
        self.downBtn_3.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../graphics/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downBtn_3.setIcon(icon6)
        self.downBtn_3.setIconSize(QtCore.QSize(32, 32))
        self.downBtn_3.setCheckable(True)
        self.downBtn_3.setObjectName("downBtn_3")
        self.gridLayout_3.addWidget(self.downBtn_3, 0, 1, 1, 1)
        self.centerBtn_3 = QtWidgets.QToolButton(self.centralwidget)
        self.centerBtn_3.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../graphics/circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.centerBtn_3.setIcon(icon7)
        self.centerBtn_3.setIconSize(QtCore.QSize(32, 32))
        self.centerBtn_3.setCheckable(True)
        self.centerBtn_3.setObjectName("centerBtn_3")
        self.gridLayout_3.addWidget(self.centerBtn_3, 1, 1, 1, 1)
        self.upRightBtn_3 = QtWidgets.QToolButton(self.centralwidget)
        self.upRightBtn_3.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../graphics/upLeft.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upRightBtn_3.setIcon(icon8)
        self.upRightBtn_3.setIconSize(QtCore.QSize(32, 32))
        self.upRightBtn_3.setCheckable(True)
        self.upRightBtn_3.setObjectName("upRightBtn_3")
        self.gridLayout_3.addWidget(self.upRightBtn_3, 2, 0, 1, 1)
        self.leftBtn_3 = QtWidgets.QToolButton(self.centralwidget)
        self.leftBtn_3.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../graphics/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftBtn_3.setIcon(icon9)
        self.leftBtn_3.setIconSize(QtCore.QSize(32, 32))
        self.leftBtn_3.setCheckable(True)
        self.leftBtn_3.setObjectName("leftBtn_3")
        self.gridLayout_3.addWidget(self.leftBtn_3, 1, 2, 1, 1)
        self.upBtn_3 = QtWidgets.QToolButton(self.centralwidget)
        self.upBtn_3.setAutoFillBackground(True)
        self.upBtn_3.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../graphics/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upBtn_3.setIcon(icon10)
        self.upBtn_3.setIconSize(QtCore.QSize(32, 32))
        self.upBtn_3.setCheckable(True)
        self.upBtn_3.setObjectName("upBtn_3")
        self.gridLayout_3.addWidget(self.upBtn_3, 2, 1, 1, 1)
        self.downLeftBtn_3 = QtWidgets.QToolButton(self.centralwidget)
        self.downLeftBtn_3.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../graphics/downLeft.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downLeftBtn_3.setIcon(icon11)
        self.downLeftBtn_3.setIconSize(QtCore.QSize(32, 32))
        self.downLeftBtn_3.setCheckable(True)
        self.downLeftBtn_3.setObjectName("downLeftBtn_3")
        self.gridLayout_3.addWidget(self.downLeftBtn_3, 0, 2, 1, 1)
        self.formLayout_3.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.gridLayout_3)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.applyBtn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.applyBtn_3.setObjectName("applyBtn_3")
        self.horizontalLayout_3.addWidget(self.applyBtn_3)
        self.revertBtn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.revertBtn_3.setObjectName("revertBtn_3")
        self.horizontalLayout_3.addWidget(self.revertBtn_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 948, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionSelect_All = QtWidgets.QAction(MainWindow)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionEdit_Song_Info = QtWidgets.QAction(MainWindow)
        self.actionEdit_Song_Info.setObjectName("actionEdit_Song_Info")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionSongInfo = QtWidgets.QAction(MainWindow)
        self.actionSongInfo.setObjectName("actionSongInfo")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLevel_Info = QtWidgets.QAction(MainWindow)
        self.actionLevel_Info.setObjectName("actionLevel_Info")
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addAction(self.actionSave_As)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionClose)
        self.menu_Edit.addAction(self.actionCut)
        self.menu_Edit.addAction(self.actionCopy)
        self.menu_Edit.addAction(self.actionPaste)
        self.menu_Edit.addAction(self.actionSelect_All)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionLevel_Info)
        self.menu_Edit.addAction(self.actionSongInfo)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.betaLabel_3.setText(_translate("MainWindow", "Beat"))
        self.timeLabel_3.setText(_translate("MainWindow", "Time (in ms)"))
        self.noteIndexLabel_3.setText(_translate("MainWindow", "Position"))
        self.noteLayerLabel_3.setText(_translate("MainWindow", "Height"))
        self.noteTypeLabel_3.setText(_translate("MainWindow", "Note Type"))
        self.cutDirLabel_3.setText(_translate("MainWindow", "Cut Direction"))
        self.applyBtn_3.setText(_translate("MainWindow", "Apply"))
        self.revertBtn_3.setText(_translate("MainWindow", "Revert"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
        self.action_Save.setText(_translate("MainWindow", "&Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionSelect_All.setText(_translate("MainWindow", "Select All"))
        self.actionEdit_Song_Info.setText(_translate("MainWindow", "Edit Song Info"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionSongInfo.setText(_translate("MainWindow", "SongInfo"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionLevel_Info.setText(_translate("MainWindow", "Level Info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

