# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\noteStatUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(443, 536)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.betaLabel = QtWidgets.QLabel(Form)
        self.betaLabel.setObjectName("betaLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.betaLabel)
        self.beatIn = QtWidgets.QDoubleSpinBox(Form)
        self.beatIn.setObjectName("beatIn")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.beatIn)
        self.timeLabel = QtWidgets.QLabel(Form)
        self.timeLabel.setObjectName("timeLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.timeLabel)
        self.timeIn = QtWidgets.QDoubleSpinBox(Form)
        self.timeIn.setObjectName("timeIn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.timeIn)
        self.cutDirLabel = QtWidgets.QLabel(Form)
        self.cutDirLabel.setObjectName("cutDirLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.cutDirLabel)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.upLeftBtn = QtWidgets.QToolButton(Form)
        self.upLeftBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("upRight.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upLeftBtn.setIcon(icon)
        self.upLeftBtn.setIconSize(QtCore.QSize(32, 32))
        self.upLeftBtn.setCheckable(True)
        self.upLeftBtn.setObjectName("upLeftBtn")
        self.gridLayout.addWidget(self.upLeftBtn, 2, 2, 1, 1)
        self.downRightBtn = QtWidgets.QToolButton(Form)
        self.downRightBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("downRight.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downRightBtn.setIcon(icon1)
        self.downRightBtn.setIconSize(QtCore.QSize(32, 32))
        self.downRightBtn.setCheckable(True)
        self.downRightBtn.setObjectName("downRightBtn")
        self.gridLayout.addWidget(self.downRightBtn, 0, 0, 1, 1)
        self.rightBtn = QtWidgets.QToolButton(Form)
        self.rightBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightBtn.setIcon(icon2)
        self.rightBtn.setIconSize(QtCore.QSize(32, 32))
        self.rightBtn.setCheckable(True)
        self.rightBtn.setObjectName("rightBtn")
        self.gridLayout.addWidget(self.rightBtn, 1, 0, 1, 1)
        self.downBtn = QtWidgets.QToolButton(Form)
        self.downBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downBtn.setIcon(icon3)
        self.downBtn.setIconSize(QtCore.QSize(32, 32))
        self.downBtn.setCheckable(True)
        self.downBtn.setObjectName("downBtn")
        self.gridLayout.addWidget(self.downBtn, 0, 1, 1, 1)
        self.centerBtn = QtWidgets.QToolButton(Form)
        self.centerBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.centerBtn.setIcon(icon4)
        self.centerBtn.setIconSize(QtCore.QSize(32, 32))
        self.centerBtn.setCheckable(True)
        self.centerBtn.setObjectName("centerBtn")
        self.gridLayout.addWidget(self.centerBtn, 1, 1, 1, 1)
        self.upRightBtn = QtWidgets.QToolButton(Form)
        self.upRightBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("upLeft.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upRightBtn.setIcon(icon5)
        self.upRightBtn.setIconSize(QtCore.QSize(32, 32))
        self.upRightBtn.setCheckable(True)
        self.upRightBtn.setObjectName("upRightBtn")
        self.gridLayout.addWidget(self.upRightBtn, 2, 0, 1, 1)
        self.leftBtn = QtWidgets.QToolButton(Form)
        self.leftBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftBtn.setIcon(icon6)
        self.leftBtn.setIconSize(QtCore.QSize(32, 32))
        self.leftBtn.setCheckable(True)
        self.leftBtn.setObjectName("leftBtn")
        self.gridLayout.addWidget(self.leftBtn, 1, 2, 1, 1)
        self.upBtn = QtWidgets.QToolButton(Form)
        self.upBtn.setAutoFillBackground(True)
        self.upBtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upBtn.setIcon(icon7)
        self.upBtn.setIconSize(QtCore.QSize(32, 32))
        self.upBtn.setCheckable(True)
        self.upBtn.setObjectName("upBtn")
        self.gridLayout.addWidget(self.upBtn, 2, 1, 1, 1)
        self.downLeftBtn = QtWidgets.QToolButton(Form)
        self.downLeftBtn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("downLeft.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downLeftBtn.setIcon(icon8)
        self.downLeftBtn.setIconSize(QtCore.QSize(32, 32))
        self.downLeftBtn.setCheckable(True)
        self.downLeftBtn.setObjectName("downLeftBtn")
        self.gridLayout.addWidget(self.downLeftBtn, 0, 2, 1, 1)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.gridLayout)
        self.indexIn = QtWidgets.QSpinBox(Form)
        self.indexIn.setObjectName("indexIn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.indexIn)
        self.layerIn = QtWidgets.QSpinBox(Form)
        self.layerIn.setObjectName("layerIn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.layerIn)
        self.noteIndexLabel = QtWidgets.QLabel(Form)
        self.noteIndexLabel.setObjectName("noteIndexLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.noteIndexLabel)
        self.noteLayerLabel = QtWidgets.QLabel(Form)
        self.noteLayerLabel.setObjectName("noteLayerLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.noteLayerLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mineBtn = QtWidgets.QToolButton(Form)
        self.mineBtn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("mine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mineBtn.setIcon(icon9)
        self.mineBtn.setIconSize(QtCore.QSize(32, 32))
        self.mineBtn.setCheckable(True)
        self.mineBtn.setObjectName("mineBtn")
        self.horizontalLayout_2.addWidget(self.mineBtn)
        self.redBtn = QtWidgets.QToolButton(Form)
        self.redBtn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.redBtn.setIcon(icon10)
        self.redBtn.setIconSize(QtCore.QSize(32, 32))
        self.redBtn.setCheckable(True)
        self.redBtn.setObjectName("redBtn")
        self.horizontalLayout_2.addWidget(self.redBtn)
        self.bluBtn = QtWidgets.QToolButton(Form)
        self.bluBtn.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bluBtn.setIcon(icon11)
        self.bluBtn.setIconSize(QtCore.QSize(32, 32))
        self.bluBtn.setObjectName("bluBtn")
        self.horizontalLayout_2.addWidget(self.bluBtn)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.noteTypeLabel = QtWidgets.QLabel(Form)
        self.noteTypeLabel.setObjectName("noteTypeLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.noteTypeLabel)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.applyBtn = QtWidgets.QPushButton(Form)
        self.applyBtn.setObjectName("applyBtn")
        self.horizontalLayout.addWidget(self.applyBtn)
        self.revertBtn = QtWidgets.QPushButton(Form)
        self.revertBtn.setObjectName("revertBtn")
        self.horizontalLayout.addWidget(self.revertBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.betaLabel.setText(_translate("Form", "Beat"))
        self.timeLabel.setText(_translate("Form", "Time (in ms)"))
        self.cutDirLabel.setText(_translate("Form", "CutDirection"))
        self.noteIndexLabel.setText(_translate("Form", "Position"))
        self.noteLayerLabel.setText(_translate("Form", "Height"))
        self.noteTypeLabel.setText(_translate("Form", "NoteType"))
        self.applyBtn.setText(_translate("Form", "Apply"))
        self.revertBtn.setText(_translate("Form", "Revert"))

